import { BookCard1 } from "@/types/BookCardTypes";

export const phasesUser: BookCard1[] = [
  {
    Id:"1",
    imageuser: "/images/userprofile/img1.png",
    place: "Mirissa",
    date: "Wed , December 25",
    time: "03:00 PM - 07:00 PM",
    bookingNO: "#12345",
    status: "Completed",
    adultPrice:"900",
    childPrice:"600",
    totalPrice:"1500",
  },
  {
    Id: "2",
    imageuser: "/images/userprofile/img2.png",
    place: "Udawalawa",
    date: "Wed , December 25",
    time: "03:00 PM - 07:00 PM",
    bookingNO: "#12345",
    status: "Completed",
    adultPrice:"900",
    childPrice:"600",
    totalPrice:"1500",
  },
  {
    Id: "3",
    imageuser: "/images/userprofile/img3.png",
    place: "Yala Safari",
    date: "Wed , December 25",
    time: "03:00 PM - 07:00 PM",
    bookingNO: "#12345",
    status: "Completed",
    adultPrice:"900",
    childPrice:"600",
    totalPrice:"1500",
  },
  {
    Id: "4",
    imageuser: "/images/userprofile/img5.png",
    place: "Ella",
    date: "Wed , December 25",
    time: "03:00 PM - 07:00 PM",
    bookingNO: "#12345",
    status: "Completed",
    adultPrice:"900",
    childPrice:"600",
    totalPrice:"1500",
  },
  {
    Id: "5",
    imageuser: "/images/userprofile/img4.png",
    place: "Kithulgala",
    date: "Wed , December 25",
    time: "03:00 PM - 07:00 PM",
    bookingNO: "#12345",
    status: "Completed",
    adultPrice:"900",
    childPrice:"600",
    totalPrice:"1500",
  },
  {
    Id: "6",
    imageuser: "/images/userprofile/img2.png",
    place: "Udawalawa",
    date: "Wed , December 25",
    time: "03:00 PM - 07:00 PM",
    bookingNO: "#12345",
    status: "Completed",
    adultPrice:"900",
    childPrice:"600",
    totalPrice:"1500",
  },
  {
    Id: "7",
    imageuser: "/images/userprofile/img3.png",
    place: "Yala Safari",
    date: "Wed , December 25",
    time: "03:00 PM - 07:00 PM",
    bookingNO: "#12345",
    status: "Completed",
    adultPrice:"900",
    childPrice:"600",
    totalPrice:"1500",
  },
  {
    Id: "8",
    imageuser: "/images/userprofile/img5.png",
    place: "Ella",
    date: "Wed , December 25",
    time: "03:00 PM - 07:00 PM",
    bookingNO: "#12345",
    status: "Completed",
    adultPrice:"900",
    childPrice:"600",
    totalPrice:"1500",
  },
  {
    Id: "9",
    imageuser: "/images/userprofile/img4.png",
    place: "Kithulgala",
    date: "Wed , December 25",
    time: "03:00 PM - 07:00 PM",
    bookingNO: "#12345",
    status: "Completed",
    adultPrice:"900",
    childPrice:"600",
    totalPrice:"1500",
  },
  {
    Id: "10",
    imageuser: "/images/userprofile/img1.png",
    place: "Mirissa",
    date: "Wed , December 25",
    time: "03:00 PM - 07:00 PM",
    bookingNO: "#12345",
    status: "Completed",
    adultPrice:"900",
    childPrice:"600",
    totalPrice:"1500",
  }
];
